name: Cross-Compile Aria2 via Dockerfile.mingw & Publish Release

on: [push,pull_request,workflow_dispatch]

jobs:
  build-via-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v6

    - name: Modify connection limit
      run: |
        sed -i 's/"16"/"128"/g' src/OptionHandlerFactory.cc

    - name: Build Docker Image
      run: |
        docker build -t aria2-mingw-image -f Dockerfile.mingw .

    - name: Extract Binary from Docker Container
      run: |
        docker run --rm -v "$PWD/output":/out aria2-mingw-image cp /aria2/src/aria2c.exe /out

    - name: Upload Artifact
      uses: actions/upload-artifact@v6
      with:
        name: aria2c-win64-custom
        path: output/aria2c.exe
        retention-days: 7 
